### ISSUE TITLE
Impact of masks and depth

### ISSUE THREAD

**Issue by rakesh-reddy95** [Make-A-Protagonist/Make-A-Protagonist#10]
What happens if I don't use the masks and depth during inference. What is the impact of masks/depth for generating video.

**Comment by HeliosZhao** [comment]
Hi, thanks for your interest in our work. 

Please refer to Fig. 7 and Tab. 2 in Sec 4.3 Ablation Studies. The qualitative and quantative results are shown when removing depth (w.o. ControlNet) and masks (w.o. DALL-E 2 Prior).

**Comment by rakesh-reddy95** [comment]
Got it, thanks. I have tested the impact and seems as written.
