### ISSUE TITLE
请教一下，应用参考图片替换主体效果却不怎么成功，效果不是很好

### ISSUE THREAD

**Issue by chenjun0210** [Make-A-Protagonist/Make-A-Protagonist#11]
1. 我训练了yanzi模型，并把参考图片替换成高启强，并不能很好的控制生成高启强的视频效果。后来替换了川普图片，也不行，只有把promt 也改成特朗普，效果才可以.
2. 我自己训练了一个39帧得动态表情（一只猫）做了两组实验：
（1）然后promot替换成不同的动物名字，如狗、狮子、老虎。reference指定同一张狗图片，然后生成的视频和promt的不同名词是对应的，没有受到参考图片的影响.
（2）然后找了几张对应的名字的图片作为参考图，但是生成的视频主体和参考图片不是一摸一样。

训练参数：图片高宽 480， frames = 39 
推理：source_protagonist: false & source_background: false

**Comment by HeliosZhao** [comment]
> 1. 我训练了yanzi模型，并把参考图片替换成高启强，并不能很好的控制生成高启强的视频效果。后来替换了川普图片，也不行，只有把promt 也改成特朗普，效果才可以.

目前对人物的脸部控制是有缺陷，我们也尝试使用了高启强图片，效果不太好。
使用文本和图像一起控制可以改善脸部的效果，比如特朗普和马斯克。

> 2. 我自己训练了一个39帧得动态表情（一只猫）做了两组实验：
>    （1）然后promot替换成不同的动物名字，如狗、狮子、老虎。reference指定同一张狗图片，然后生成的视频和promt的不同名词是对应的，没有受到参考图片的影响.
>    （2）然后找了几张对应的名字的图片作为参考图，但是生成的视频主体和参考图片不是一摸一样。
> 
> 训练参数：图片高宽 480， frames = 39 推理：source_protagonist: false & source_background: false

对于prompt的名词，我们在Appendix D Limitations 和 Fig. 10中进行了研究。建议使用对应reference的prompt，或使用superclass，例如animal，作为prompt。
另外，T2I的模型使用768的图像尺寸，因此，finetune的时候使用不同的尺寸可能会影响效果。

**Comment by chenjun0210** [comment]
谢谢，我试试。
