### ISSUE TITLE
Frame to frame consistency

### ISSUE THREAD

**Issue by rakesh-reddy95** [Make-A-Protagonist/Make-A-Protagonist#13]
Thanks for the code. I have edited few videos and seen that the frame-frame consistency is not that smooth like the source video. And looks like the frame is not constant ( like the camera angle is shaking). Do you have any ideas to improve this?

**Comment by HeliosZhao** [comment]
Hi, I am not sure but I conjecture it may be due to the complex source video. In our experiments, we use source videos that have no or slight camera angle change.

Can you show some results so we can help you to improve the frame consistency?

**Comment by rakesh-reddy95** [comment]
https://github.com/HeliosZhao/Make-A-Protagonist/assets/20672248/c9d2a37c-4b24-4450-9737-7d9049ef6d6c

![sample-500-s0-e50-seed33](https://github.com/HeliosZhao/Make-A-Protagonist/assets/20672248/b1a2957a-132b-44ea-bd90-b78aaab3bdd6)

**Comment by rakesh-reddy95** [comment]
@HeliosZhao Here are the results. I used the cat walking as the source video and a dog replaced.

**Comment by HeliosZhao** [comment]
@rakesh-reddy95 From the source video and the results, there might be two reasons impairing the performance. 
- The first is the frame rate. The length of the source video is 10 seconds while the model only uses 8 frames. The frame interval seems to be 1 second. Such a large interval will lead to large and inconsistent motion. It is better to visualize the source video with such frame interval to check if the source video is consistent.
- The second is the aspect ratio. The model uses a resolution of 768x768, the aspect ratio is 1:1. Instead, the aspect ratio of source video is around 16:9. If the source video without cropping is directly fed into the model, it will be resized to 768x768, change the aspect ratio to 1:1. Therefore, cropping the source video into a square would help to generate a better result.

**Comment by rakesh-reddy95** [comment]
@HeliosZhao If I keep the same frame rate and 1:1 aspect ratio for the source video here are the generated results.


https://github.com/HeliosZhao/Make-A-Protagonist/assets/20672248/431a710f-f7d9-4a5a-9769-edbaa7e0a589

![sample-200-s0-e50-seed33 (14)](https://github.com/HeliosZhao/Make-A-Protagonist/assets/20672248/af505aca-2826-44cb-b5fe-f338158a3665)

**Comment by rakesh-reddy95** [comment]
@HeliosZhao If I keep the fps consistent (@fps) and aspect ratio 1:1 for the source video, here are the results.


https://github.com/HeliosZhao/Make-A-Protagonist/assets/20672248/feecf6d5-fa3a-4426-b05a-df819783d234

![sample-200-s0-e50-seed33 (14)](https://github.com/HeliosZhao/Make-A-Protagonist/assets/20672248/2401eea9-f61c-4373-bef3-754b0494b63a)

**Comment by HeliosZhao** [comment]
I think the new result has better consistency. At least the camera angle is not shaking. 

For your case, you can set `source_background=True` and change the `controlnet_conditioning_scale` to refine the result.

**Comment by rakesh-reddy95** [comment]
@HeliosZhao  I see some consistency after making the controlnet_conditioning_scale to [.5,.5]. May I know the exact significance of this parameter?

**Comment by HeliosZhao** [comment]
The two values are the weight for ControlNet feature from the pose signal and depth signal, respectively. The larger the weight is, the more control information will be used. 

For your case, the pose control may not influence the performance. You can set the first value as 0 and tune the second value.

**Comment by rakesh-reddy95** [comment]
Got it, thanks @HeliosZhao.
