### ISSUE TITLE
Improvements in the generation

### ISSUE THREAD

**Issue by rakesh-reddy95** [Make-A-Protagonist/Make-A-Protagonist#14]
Hi @HeliosZhao 

After going through the complete code and experiments, I see the following issues.
1. Issues with the generation quality and long video generation.
2. Certainly some part of the background from the source video is missing in the target video though we are using the masks and editing only the protagonist.

Plans to improve:
1. Can we use temporalNet from ControlNet as a guidance to improve the consistency.
2. Can we use pretrained text to video models or train this architecture on videos dataset to better learn the patterns. As the current one used is T2I ( Text to Image) the frame-to-frame consistency is low compare to the source videos.
3. Can we use any other additional guidance for the better generation?
4. Can we use weighted temporal attention, I see we calculate the attention with single frame. Can we use moving weighted average so that the information is preserved ( RNN kind of architecture here).

Can you help answering these? Thanks in advance.

**Comment by rakesh-reddy95** [comment]
Following up, can we use motion vector for the consistent video generation. 
https://arxiv.org/pdf/2306.02018.pdf - mentioned in this paper.

**Comment by HeliosZhao** [comment]
Hi @rakesh-reddy95 , thanks a lot for your questions and suggestions.

> 1. Can we use temporalNet from ControlNet as a guidance to improve the consistency.

Yes, you can also include ControlNet with temporal layers in the training. 

> 2. Can we use pretrained text to video models or train this architecture on videos dataset to better learn the patterns. As the current one used is T2I ( Text to Image) the frame-to-frame consistency is low compare to the source videos.

The pre-trained generative model should be able to include visual information (CLIP image embedding). Currently, Stable UnCLIP is the only public model with this ability. If there exists a T2V model that can leverage visual information, you can also use it as initialization.

> 3. Can we use any other additional guidance for the better generation?

More ControlNet models (e.g., sketch) can be used.  

> 4. Can we use weighted temporal attention, I see we calculate the attention with single frame. Can we use moving weighted average so that the information is preserved ( RNN kind of architecture here).

I am not familiar with the method you mentioned. Can you provide a paper using this?

> 5. Motion vector

Sure. Motion vector can be used as another control signal. You can train a ControlNet model with this signal and use it in training or inference.

**Comment by rakesh-reddy95** [comment]
@HeliosZhao 
Thank you for the responses. 
4. I didn't see any paper with this, but was just an idea.

Also, can you please provide the training scripts for controlnet training and saving only the controlnet weights. I see that the weights are provided and the training scripts is said to be released soon in the README.md. Also may I know the data you have used to train the depth controlnet model and pose controlnet model?

**Comment by HeliosZhao** [comment]
We are cleaning the code for ControlNet training and will release it soon. 

We use COCO2017 training set to train the depth and pose model.

**Comment by rakesh-reddy95** [comment]
@HeliosZhao Hello, I'm getting below error while training the controlnet from diffusers. (https://github.com/huggingface/diffusers/tree/v0.15.0/examples/controlnet) 
ValueError: class_labels should be provided when num_class_embeds > 0

I see we are not passing any class_labels in the training script of controlnet. While I see that in your inference pipeline. May I know what should I pass for class_labels while I'm training the depth/pose/edge models. Or should I use the "class_embed_type": null instead of "projection"

**Comment by HeliosZhao** [comment]
Hi @rakesh-reddy95 , we input zeros as `class_labels` to ControlNet and input the CLIP image embedding as `class_labels` to UNet.

**Comment by rakesh-reddy95** [comment]
@HeliosZhao Can you provide just that part of the script? initiating zeros for controlnet , and clip image embedding to UNet so that I can be able to pass?

**Comment by HeliosZhao** [comment]
The ControlNet training code is released [HERE](https://github.com/HeliosZhao/ControlNet-Stable-UnCLIP). Feel free to use.

**Comment by rakesh-reddy95** [comment]
Awesome, that helps for further experiments. Thank you.
