### ISSUE TITLE
ModuleNotFoundError: No module named 'groundingdino'

### ISSUE THREAD

**Issue by hzlhzlhzlhzl** [Make-A-Protagonist/Make-A-Protagonist#18]
I get this module import error when I attempt to run the “python experts/grounded_sam_inference.py -d data/car-turn/images/0000.jpg -t suzuki jimny”

**Comment by HeliosZhao** [comment]
Hi, 

You should first install the GroundedSAM with
```
cd experts/GroundedSAM
pip install -e GroundingDINO
pip install -e segment_anything
```

I think it will fix this problem.
