### ISSUE TITLE
Is BLIP2 extracting the image description or the video description?

### ISSUE THREAD

**Issue by culeao** [Make-A-Protagonist/Make-A-Protagonist#3]
The official BLIP2 is description extraction for image, but your paper mentions description extraction for videos, can you explain how to do that exactly?

**Comment by HeliosZhao** [comment]
Hi, Thanks for your interest in our work.

As mentioned in Sec.3.2, we extract the visual feature of each frame with the image encoder of BLIP-2, and then concatenate all the visual tokens and feed them into the Q-Former.

You may also refer to the code in [`experts/BLIP2/blip_video_model.py`](https://github.com/Make-A-Protagonist/Make-A-Protagonist/blob/2d52fbd1af92e28505e408675bf95f7c2746432f/experts/BLIP2/blip_video_model.py#L47)
