### ISSUE TITLE
Math formula of DDIM Inversion with respect to v-parameterization

### ISSUE THREAD

**Issue by Tianhao-Qi** [Make-A-Protagonist/Make-A-Protagonist#4]
As the title describes, how to derive the math formula of DDIM Inversion with respect to v-parameterization in original paper?

**Comment by HeliosZhao** [comment]
Hi, 

According to [paper](https://arxiv.org/abs/2202.00512) and [code](https://github.com/huggingface/diffusers/blob/c13dbd5c3a53017d27de35ad77b8d57f04c8ec7c/src/diffusers/schedulers/scheduling_ddim.py#L331), for v-parameterization, the predicted sample $\hat{z_t}$ and noise $\hat{\varepsilon_\theta}$ are obtained from the model prediction $\varepsilon_\theta$:
- $\hat{z_t}=\sqrt{\alpha_t} z_t - \sqrt{\beta_t} \varepsilon_\theta$
- $\hat{\varepsilon_\theta}=\sqrt{\beta_t} z_t + \sqrt{\alpha_t} \varepsilon_\theta$

Then DDIM is derived from $\hat{z_t}$ and $\hat{\varepsilon_\theta}$:
- $z_{t-1} = \sqrt{\alpha_{t-1}} \hat{z_t} + \sqrt{\beta_{t-1}}  \hat{\varepsilon_\theta}$

For DDIM inversion with v-parameterization, similar to DDIM, we first estimate $\hat{z_t}$ and $\hat{\varepsilon_\theta}$, then estimate the next timestamp:
- $z_{t+1} = \sqrt{\alpha_{t+1}} \hat{z_t} + \sqrt{\beta_{t+1}}  \hat{\varepsilon_\theta}$

We will update the formula in the next revision.
