### ISSUE TITLE
progressbar version？

### ISSUE THREAD

**Issue by willis** [Make-A-Protagonist/Make-A-Protagonist#5]
(Text-video) E:\git\Make-A-Protagonist>python experts/xmem_inference.py -d data/bird-forest/images -v bird-forest --mask_dir bird.mask
Output path not provided. By default saving to the mask dir
save_all is forced to be true in generic evaluation mode.
Hyperparameters read from the model weights: C^k=64, C^v=512, C^h=64
Single object mode: False
Traceback (most recent call last):
  File "E:\git\Make-A-Protagonist\experts\xmem_inference.py", line 103, in <module>
    for vid_reader in progressbar(meta_loader, max_value=len(meta_dataset), redirect_stdout=True):
TypeError: 'module' object is not callable

(Text-video) E:\git\Make-A-Protagonist>pip list|grep progressbar
progressbar             2.5

**Comment by HeliosZhao** [comment]
Hi, we use `progressbar2==4.2.0`. Thanks for the reminder, we have updated the `requirements.txt`.
