### ISSUE TITLE
Demo page turns out to be 'No interface is running right now'

### ISSUE THREAD

**Issue by EvelynWang-0423** [Make-A-Protagonist/Make-A-Protagonist#7]
The project demo page:https://60a373ddc34b235c06.gradio.live/
turns out to be 'No interface is running right now'.
![image](https://github.com/Make-A-Protagonist/Make-A-Protagonist/assets/84950843/6fa64d83-ad73-4a9c-ac13-579a6a2221d1)

**Comment by HeliosZhao** [comment]
Hi, thanks for your interest in our work. We have updated the demo. Now it is on [Hugging Face Sapce](https://huggingface.co/spaces/Make-A-Protagonist/Make-A-Protagonist-inference). Feel free to use it!
